# Generated by Django 3.2.9 on 2022-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosVenta',
            fields=[
                ('venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=14)),
                ('fecha_venta', models.CharField(max_length=9)),
                ('vendedor', models.CharField(max_length=20)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
    ]
