# Generated by Django 3.2.9 on 2022-07-18 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IngresosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosVenta',
            fields=[
                ('venta', models.BigIntegerField(default=0, primary_key=True, serialize=False)),
                ('fecha_venta', models.CharField(max_length=20)),
                ('vendedor', models.CharField(max_length=200)),
                ('estado', models.IntegerField(default=0)),
                ('nit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IngresosApp.clientes')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=75)),
                ('nit', models.CharField(max_length=14)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(default=0)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaApp.datosventa')),
            ],
            options={
                'verbose_name': 'detalle',
                'verbose_name_plural': 'detalles',
            },
        ),
    ]
