# Generated by Django 3.2.9 on 2022-07-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0002_alter_datosventa_vendedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datosventa',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
    ]
