# Generated by Django 4.0.2 on 2022-07-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
        ('VentaApp', '0004_alter_datosventa_fecha_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosventa',
            name='nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IngresosApp.clientes'),
        ),
    ]
