# Generated by Django 4.0.2 on 2022-07-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0005_alter_datosventa_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosventa',
            name='nit',
            field=models.CharField(max_length=14),
        ),
    ]
