# Generated by Django 4.0.2 on 2022-07-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaApp', '0006_alter_datosventa_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta', models.BigIntegerField()),
                ('codigo', models.CharField(max_length=75)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.FloatField()),
                ('estado', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'detalle',
                'verbose_name_plural': 'detalles',
            },
        ),
    ]
