# Generated by Django 3.2.9 on 2022-07-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
        ('VentaApp', '0007_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosventa',
            name='nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IngresosApp.clientes'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VentaApp.datosventa'),
        ),
    ]
