# Generated by Django 3.2.9 on 2022-07-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAnulacion',
            fields=[
                ('venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=14)),
                ('cliente', models.CharField(max_length=250)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(max_length=850)),
                ('fecha_anulacion', models.DateField()),
                ('usuario', models.CharField(max_length=200)),
                ('fecha_sistema', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'datosanulacion',
                'verbose_name_plural': 'datosanulaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleAnulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=14)),
                ('codigo', models.CharField(max_length=75)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(default=0)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnularApp.datosanulacion')),
            ],
            options={
                'verbose_name': 'detalleanulacion',
                'verbose_name_plural': 'detalleanulaciones',
            },
        ),
    ]
