# Generated by Django 3.2.9 on 2022-07-22 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnularApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleanulacion',
            name='fecha_anulacion',
            field=models.DateField(default=datetime.date(2022, 7, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleanulacion',
            name='fecha_sistema',
            field=models.DateTimeField(default=datetime.date(2022, 7, 22)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleanulacion',
            name='usuario',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
