# Generated by Django 3.2.9 on 2022-07-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoCheque',
            fields=[
                ('venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=14)),
                ('fecha', models.CharField(max_length=25)),
                ('numero_cheque', models.IntegerField()),
                ('banco', models.CharField(max_length=250)),
                ('fecha_cheque', models.CharField(max_length=25)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(max_length=75)),
                ('abono', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verificador', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
                ('fecha_sistema', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'pagocheque',
                'verbose_name_plural': 'pagocheques',
            },
        ),
    ]
