# Generated by Django 3.2.9 on 2022-07-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0002_pagocheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocheque',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
