# Generated by Django 3.2.9 on 2022-07-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0004_pagotarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='observaciones',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
