# Generated by Django 3.2.9 on 2022-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0005_pagotarjeta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagotarjeta',
            name='tipo_tarjeta',
            field=models.CharField(default=' ', max_length=75),
            preserve_default=False,
        ),
    ]
