# Generated by Django 3.2.9 on 2022-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0006_pagotarjeta_tipo_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDeposito',
            fields=[
                ('venta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=14)),
                ('fecha', models.CharField(max_length=25)),
                ('tipo_pago', models.CharField(max_length=75)),
                ('numero_boleta', models.CharField(max_length=16)),
                ('banco', models.CharField(max_length=250)),
                ('monto_deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_deposito', models.CharField(max_length=25)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verificador', models.IntegerField()),
                ('observaciones', models.CharField(max_length=250)),
                ('estado', models.IntegerField()),
                ('usuario', models.CharField(max_length=200)),
                ('fecha_sistema', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'pagotarjeta',
                'verbose_name_plural': 'pagotarjetas',
            },
        ),
    ]
