# Generated by Django 4.0.2 on 2022-07-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PagoApp', '0009_notacredito_notacredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacredito',
            name='notacredito',
        ),
    ]
