# Generated by Django 4.0.2 on 2022-06-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=75)),
                ('referencia', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('precio_venta', models.FloatField()),
                ('descuento', models.FloatField(blank=True)),
                ('precio_compra', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos')),
                ('usuario', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
