# Generated by Django 4.0.2 on 2022-06-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='codigo',
        ),
    ]
