# Generated by Django 4.0.2 on 2022-07-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='nit',
            field=models.CharField(default=' ', max_length=14),
            preserve_default=False,
        ),
    ]
