# Generated by Django 3.2.9 on 2022-07-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cuenta',
        ),
    ]
