# Generated by Django 4.0.2 on 2022-06-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulos',
            options={'verbose_name': 'articulo', 'verbose_name_plural': 'articulos'},
        ),
    ]
