# Generated by Django 4.0.2 on 2022-06-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0002_alter_articulos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio_compra',
            field=models.FloatField(),
        ),
    ]
