# Generated by Django 3.2.9 on 2022-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0003_enviostarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosDeposito',
            fields=[
                ('verificador', models.IntegerField(primary_key=True, serialize=False)),
                ('remitente', models.CharField(max_length=250)),
                ('direccion_remitente', models.CharField(max_length=250)),
                ('telefono_remitente', models.CharField(max_length=9)),
                ('destinatario', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('venta', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=75)),
                ('numero_tarjeta', models.IntegerField()),
                ('banco', models.CharField(max_length=250)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autorizacion', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(max_length=75)),
                ('usuario', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'enviotarjeta',
                'verbose_name_plural': 'enviotarjetas',
            },
        ),
    ]
