# Generated by Django 4.0.2 on 2022-06-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0003_alter_articulos_precio_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='descuento',
            field=models.FloatField(),
        ),
    ]
