# Generated by Django 3.2.9 on 2022-07-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0004_enviosdeposito'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviosdeposito',
            options={'verbose_name': 'enviosdeposito', 'verbose_name_plural': 'enviosdepositos'},
        ),
        migrations.RenameField(
            model_name='enviosdeposito',
            old_name='total',
            new_name='monto_deposito',
        ),
        migrations.RenameField(
            model_name='enviosdeposito',
            old_name='autorizacion',
            new_name='numero_boleta',
        ),
        migrations.RemoveField(
            model_name='enviosdeposito',
            name='numero_tarjeta',
        ),
        migrations.AddField(
            model_name='enviosdeposito',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
