# Generated by Django 4.0.2 on 2022-07-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0005_auto_20220720_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnviosNotaCredito',
            fields=[
                ('verificador', models.IntegerField(primary_key=True, serialize=False)),
                ('notacredito', models.CharField(max_length=35)),
                ('remitente', models.CharField(max_length=250)),
                ('direccion_remitente', models.CharField(max_length=250)),
                ('telefono_remitente', models.CharField(max_length=9)),
                ('destinatario', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=14)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('venta', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=75)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.CharField(max_length=25)),
                ('fecha_fin', models.CharField(max_length=25)),
                ('observacion', models.CharField(blank=True, max_length=500)),
                ('estado', models.CharField(max_length=75)),
                ('usuario', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'enviosnotacredito',
                'verbose_name_plural': 'enviosnotacreditos',
            },
        ),
    ]
