# Generated by Django 4.0.2 on 2022-06-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0005_alter_articulos_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='existencia',
            field=models.IntegerField(default=0),
        ),
    ]
