# Generated by Django 4.0.2 on 2022-06-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0006_articulos_existencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=75)),
                ('nit', models.CharField(max_length=14)),
                ('tipo', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha_nac', models.DateField(blank=True)),
                ('cuenta', models.FloatField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('usuario', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
