# Generated by Django 4.0.2 on 2022-06-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0007_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_ingreso',
        ),
    ]
