# Generated by Django 4.0.2 on 2022-06-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0008_remove_clientes_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
