# Generated by Django 4.0.2 on 2022-06-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0009_clientes_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=75)),
                ('tipo', models.CharField(max_length=200)),
                ('remitente', models.CharField(max_length=200)),
                ('destinatario', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=75)),
                ('monto', models.FloatField(blank=True)),
                ('usuario', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'envios',
                'verbose_name_plural': 'envios',
            },
        ),
    ]
