# Generated by Django 4.0.2 on 2022-06-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IngresosApp', '0010_envios'),
    ]

    operations = [
        migrations.AddField(
            model_name='envios',
            name='guia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
